### ISSUE TITLE
Feedback's tips text are missing 

### ISSUE THREAD

**Issue by ecureuill** [solex2006/SELIProject#18]
## Expected Behavior

Every field of the accessibility forms has a related tip, presented with a **information icon**

## Current Behavior

The **information icon**  is presented without a text

## Steps to Reproduce

![image](https://user-images.githubusercontent.com/993369/76000727-dd801500-5ee2-11ea-912e-3dbfbf978d8d.png)
![image](https://user-images.githubusercontent.com/993369/76000786-f38dd580-5ee2-11ea-9977-823ebcb44da1.png)

## Possible Solution

Check the component **AccessibilityHelp**  which manage the feedbacks for the accessibility fields. 

`AccessibilityHelp from '../tools/AccessibilityHelp'
`
```
<AccessibilityHelp 
  id={'short-description-help-container'}  //id of the feedback container
  name={'shortDescriptionHelpContainer'} //name of the feedback container
  error={props.error}  //[bool] accessibility resource configuration status
  tip={props.tip}  // tip message 
/>

```

**Comment by CAndresH** [comment]
thanks camila for the suggestion the changes have been made
![image](https://user-images.githubusercontent.com/50594090/76562208-e2a90b00-6472-11ea-8790-0096d46a9143.png)

When I deploy to the server I will notify you to review the changes
![image](https://user-images.githubusercontent.com/50594090/76562284-13894000-6473-11ea-82bf-4e899ec69a23.png)
