### ISSUE TITLE
Turkish characters not accepted in "keyword" input in Information Step  

### ISSUE THREAD

**Issue by ecureuill** [solex2006/SELIProject#195]
## Current Behavior
Some turkish characters are not being accepted in keyword input text

## Steps to Reproduce

not provided

## Environment

https://vm2161.kaj.pouta.csc.fi/user

**Comment by armagan9706** [comment]
We already checked it as Turkish team. We can put Turkish letters into keyword section. Besides this, warning still remains as 5 words max but we can put more words than 5. Thanks.

**Comment by ecureuill** [comment]
Thanks for the feedback @armagan9706 .

About the keywords, this validation is part of the Information Step feature (#74) and is pending to be coded yet

**Comment by armagan9706** [comment]
Thanks for your support Camilla :)

Camilla Silva <notifications@github.com>, 9 Eyl 2020 Çar, 20:24 tarihinde
şunu yazdı:
