### ISSUE TITLE
Must select image type

### ISSUE THREAD

**Issue by ecureuill** [solex2006/SELIProject#24]
## Expected Behavior

Teacher must select the type of the image, so system could enable the field of short and long description correctly.

It was working properly [before](https://gitlab.com/ecureuill/seli/-/blob/master/SELI-Platform/imports/components/accessibility/ImageAccessibilityForm.js)
1. Initial state: Informative image only short description enabled
![image](https://user-images.githubusercontent.com/993369/76170074-5be7eb80-615d-11ea-8584-dd7c849b28a3.png)

2. Decorative image: No accessibility resources required 
![image](https://user-images.githubusercontent.com/993369/76170085-73bf6f80-615d-11ea-9426-29298c49f982.png)

3. Text: Short description
![image](https://user-images.githubusercontent.com/993369/76170098-8a65c680-615d-11ea-853b-497be895a47f.png)

4. Complex: short and long description
![image](https://user-images.githubusercontent.com/993369/76170117-a9645880-615d-11ea-89b2-2eba679eb9cf.png)

## Current Behavior

![image](https://user-images.githubusercontent.com/993369/76170152-052ee180-615e-11ea-8691-27137d42ac39.png)

## Steps to Reproduce

1. Select to configure image accessibility for the first time 
2. Don't select any type of image options
3. Write a short description
4. Save

**Comment by CAndresH** [comment]
Camila, I did not find any previous functional implementation, but the error was corrected now the system selects by default at the start "informative image"

![image](https://user-images.githubusercontent.com/50594090/76768788-817e8180-6769-11ea-907d-15ae06bbea31.png)
