### ISSUE TITLE
Image's caption position

### ISSUE THREAD

**Issue by ecureuill** [solex2006/SELIProject#25]
When teacher upload a complex image, long description field is enabled, so teacher can inform a image caption. 
Then, teacher can select if caption will be positioned above or bellow the image.
 
## Expected Behavior

It was working before
![image](https://user-images.githubusercontent.com/993369/76170698-234b1080-6163-11ea-8785-25831647224f.png)

## Current Behavior

![image](https://user-images.githubusercontent.com/993369/76170708-3362f000-6163-11ea-9ba9-be68abf9baee.png)

## Steps to Reproduce

1. Select **Complex** image 
2. Long description field and caption position should enable

**Comment by CAndresH** [comment]
Image's caption position #25 i 
Camila already added this functionality, the code of this functionality was commented by Mateo, and there are some changes in the styles made by mateo,
For now, the platform looks like this:
Teacher part:

![image](https://user-images.githubusercontent.com/50594090/76437130-1870c580-6387-11ea-9d21-26a2f2ba257f.png)


student part:
![image](https://user-images.githubusercontent.com/50594090/76436971-de072880-6386-11ea-92c5-da102c8c9a05.png)


now, these changes have been made commit on github, and the changes of all the advances I will deploy on the server every Friday so you can review them
