### ISSUE TITLE
Long description not enabled for complex image when editing accessibility configuration

### ISSUE THREAD

**Issue by ecureuill** [solex2006/SELIProject#26]
## Expected Behavior

Long description field should show for complex images when editing accessibility configuration
## Current Behavior

Long description field is hide

## Steps to Reproduce

1. Configure accessibility of an image 
2. Check complex image options and fill up long and short description
3. Save and close  
4. Select to configure accessibility for the same image
5. Accessibility form is loaded without long description field

![image](https://user-images.githubusercontent.com/993369/76170792-0a8f2a80-6164-11ea-9601-1c8f8dc0200a.png)
![image](https://user-images.githubusercontent.com/993369/76170796-14b12900-6164-11ea-96a6-f7a7490df042.png)

**Comment by CAndresH** [comment]
This option is enabled now
