### ISSUE TITLE
Activity's text editor is trapping keyboard navigators inside it

### ISSUE THREAD

**Issue by ecureuill** [solex2006/SELIProject#34]
## Expected Behavior

User can use tab to navigate in and away from text editor.

## Current Behavior

User can use tab to navigate to text editor, but **can't navigate away using tab.** 

## Steps to Reproduce

1. As a student, start an Activity in any course.
2. Navigate to text editor using TAB key
3. Use TAB key to navigate away from text editor **(failed)**

https://docs.google.com/presentation/d/1OBRtT9S3NZWK2bq9wvEzXLxcoQMxMC_CesAsUgqkUww/edit#slide=id.g65604c07eb_1_510

## Environment

Debian OS
Browser: Chrome 

## Possible Implementation
Use a11yEditor instead, styleEditor

https://gitlab.com/ecureuill/seli/-/blob/master/SELI-Platform/imports/components/tools/a11yEditor.js#L58

Use the a11yTextEditor
https://github.com/solex2006/SELIProject/blob/afcb369472877a098938317288109524205c7147/SELI-Platform/imports/components/tools/a11yEditor.js#L55

**Comment by ecureuill** [comment]
From a e-mail I've sent 

> 3) tool/a11yEditor is the text editor that I coded (DraftJS). For first prototype the purpose was to limit the editor to avoid that teacher input inaccessible texts. So, for now it enables styling (BOLD, ITALIC and UNDERLINE), block types (paragraph, headers, quotes and lists) and don't allow to paste rich text. Also, "delete" wasn't allowed because of a bug in DraftJS that breaks some of my accessibility validations. For next versions it's possible to include blocks for links, abbreviations, unusual words, etc.  
> For now, a11yEditor is used in image captions (CaptionEditor) and transcriptions of video/audio (SimpleTextEditor). But it's very important that it replace the entire text content (title / text sections) to avoid a lot of accessibility issues. 
> For now, there are 4 variants of editor: styleEditor (allow only inline styles), CaptionEditor (styles, 3 headers levels, lists and quotes), SimpleTextEditor (plain text) and FullTextEditor (all styles and block types).

**Comment by CAndresH** [comment]
Camila I changed the text editor on the student side now it is found in the bugfix / 34 branch for revision
![image](https://user-images.githubusercontent.com/50594090/78379741-749ac400-7598-11ea-85a2-51a498c9c8d8.png)
