### ISSUE TITLE
Link in Activity's instruction isn't parsed

### ISSUE THREAD

**Issue by ecureuill** [solex2006/SELIProject#35]
Link added by teacher in activity content (authoring tool) are not rendering correctly. 

## Expected Behavior

The links added by one teacher in the authoring tool must render correctly.

## Current Behavior

The links are not being rendered as links, but as texts (the <a> tag structure appears instead).

## Steps to Reproduce

Add a link in the authoring tool. Render this link.

**As a teacher**
1. Insert a Activity content
2. In instruction input, add a link using the "link button" of the text editor
3. Create the content
4. Publish the course

** As a student**
1. Navigate to the course and open the activity
2. The link is rendered not parsed.

**[SELI - Accessibility test](https://docs.google.com/presentation/d/1OBRtT9S3NZWK2bq9wvEzXLxcoQMxMC_CesAsUgqkUww/edit#slide=id.g656ec9906d_4_83) (slide 21)**

## Environment

Browser: all 

## Possible Implementation

- [ ] As stated in issue #34, it's necessary to change the text editor component for the a11yEditor.
- [ ] And [add a block type for link](https://github.com/facebook/draft-js/blob/master/examples/draft-0-10-0/link/link.html) in the a11yEditor

## Related issues
#34

**Comment by juantenesaca** [comment]
I have tested this issue and it is working ok. Could you be more specific?

**Comment by ecureuill** [comment]
@juantenesaca this have been fixed since the issue was listed (november/2019)
