### ISSUE TITLE
As a STUDENT WITH SPECIAL NEEDS I want to extend Quiz time So that I can finish the activity

### ISSUE THREAD

**Issue by ecureuill** [solex2006/SELIProject#39]
# User story

As a STUDENT WITH SPECIAL NEEDS I want to extend Quiz time So that I can finish the activity

## ACCEPTANCE CRITERIA

- [x] Scenario: Alert in Quiz with time constraint
GIVEN I'm doing a quiz 
WHEN the system alert me that the time is almost out AND I have the option to extend time AND I click the option to extend time 
THEN quiz time is extended

- [x] Scenario: Extra time option for a Quiz with time constraint
GIVEN I select to start a quiz
WHEN I click the option to extend time 
THEN quiz time is extended
 
- [x] Scenario: No time option for  a Quiz with time constraint
GIVEN I select to start a quiz
WHEN I click the option to disable time
THEN quiz time constraint is disabled.
 
# NOTES
- extra-time and no-time options depends on teacher configuration of quiz (see #40) 
- extra-time and no-time could be presented at the confirmation modal (First modal after user select to start the quiz) 
  - Cancel button
  - Start | Start with extended time | Start with no time constraint
first page of quiz 
# Glossary
STUDENT WITH SPECIAL NEEDS:
- People with physical disabilities often need more time to react, to type and to complete activities. 
- People with low vision need more time to locate things on screen and to read.  
- People who are blind and using screen readers may need more time to understand screen layouts, to find information and to operate controls. 
- People who have cognitive or language limitations need more time to read and to understand.
- People who are deaf and communicate in sign language may need more time to read information printed in text (which may be a second language for some).
- People with reading disabilities, cognitive limitations, and learning disabilities who may need more time to read or comprehend information can have additional time to read the information by pausing the content.

# Resources

- Check [Audience tab](https://docs.google.com/spreadsheets/d/1WvuabWz_LZaBUfMaUJFL_yXmXcI0nTgUBdIbXrrcbpc/edit#gid=1850215478) in Requisitos Spreadsheet.
- Filter by 2.2.1 and 2.2.3 for a list of disability profiles affected by this feature
- [WCAG 2.2.1](https://www.w3.org/WAI/WCAG21/Understanding/timing-adjustable)
- [WCAG 2.2.3](https://www.w3.org/WAI/WCAG21/Understanding/no-timing)

***************
[Optional] Developer team add your technical tasks here

- [ ] 
- [ ] 

****
[Optional] Tester team, add your test procedures here

**Comment by ecureuill** [comment]
Related commits

https://github.com/solex2006/SELIProject/commit/69c95ac8a9616a7dfd81970501d07e7c438abdd2
https://github.com/solex2006/SELIProject/commit/86bffb5242b4de53eed964cd6df2bdf51f420455

**Comment by CAndresH** [comment]
teacher configuration:
![image](https://user-images.githubusercontent.com/50594090/78810192-a4c5d680-798d-11ea-816b-232f725b9939.png)


Scenario: Alert in Quiz with time constraint
GIVEN I'm doing a quiz
WHEN the system alert me that the time is almost out AND I have the option to extend time AND I click the option to extend time
THEN quiz time is extended
![image](https://user-images.githubusercontent.com/50594090/78810264-c030e180-798d-11ea-9bdf-43210af31ecf.png)

after clicking more time
![image](https://user-images.githubusercontent.com/50594090/78810341-dd65b000-798d-11ea-80b2-4beb53b5a767.png)

Scenario: Extra time option for a Quiz with time constraint
GIVEN I select to start a quiz
WHEN I click the option to extend time
THEN quiz time is extended

![image](https://user-images.githubusercontent.com/50594090/78810504-12720280-798e-11ea-9dbe-222099bdb712.png)

you can click more time to add extra time if the option is enabled by the teacher

Scenario: No time option for a Quiz with time constraint
GIVEN I select to start a quiz
WHEN I click the option to disable time
THEN quiz time constraint is disabled.

![image](https://user-images.githubusercontent.com/50594090/78810704-4fd69000-798e-11ea-9222-d3e6912184c4.png)
you can click stop time time to disable the time if the option is enabled by the teacher

**Comment by CAndresH** [comment]
Please review the solution if possible in the develop branch: 
following the recommendations and considering requirement  #41 40, the accessibility settings are in form #3 and there are tips and feedbacks . the teacher can configure the alert time in the test, if accessibility is not configured the alert time assumes default values: (It's important that your student is warned when the time is finishing, for long duration quiz (> 20min) it's suggested a warning at 10 min. For short duration, try at half of the time, default value: half of the time constraint) likewise other time related bugs were fixed, new packages were added don't forget to do npm install
