### ISSUE TITLE
As a TEACHER I want to SETUP QUIZ WITH ALTERNATIVES TIMES CONSTRAINT 

### ISSUE THREAD

**Issue by ecureuill** [solex2006/SELIProject#40]
# User story
As a TEACHER I want to SETUP QUIZ WITH ALTERNATIVES TIMES CONSTRAINT

## ACCEPTANCE CRITERIA

- [x] Scenario: Quiz without time constraint
GIVEN that I'm configuring a quiz
WHEN I set time to 0
THEN, quiz is created without time constraint

- [x] Scenario: Quiz with time constraint and extended time 
GIVEN I'm configuring a quiz
WHEN I set time to greater than 0 
  AND select a extended time greater then 0
THEN , quiz is created with time constraint and extended time _for student with special needs_

- [x] Scenario: No-time option for a Quiz with time constraint
GIVEN I'm configuring a quiz
WHEN I set time to greater than 0 
  AND select no-time option
THEN , quiz is created with time constraint and no-time option _for student with special needs_

- [x] Scenario: Quiz with time constraint and extended time and no-time options
GIVEN I'm configuring a quiz
WHEN I set time to greater than 0 
   AND select a extended time greater then 0
  AND select no-time option
THEN , quiz is created with time constraint and extended time and no-time options _for student with special needs_
# Related Design Notes
#103 
#105

# Related features
#39 

***************
[Optional] Developer team add your technical tasks here

- [ ] 
- [ ] 

****
[Optional] Tester team, add your test procedures here

**Comment by ecureuill** [comment]
related commits

https://github.com/solex2006/SELIProject/commit/69c95ac8a9616a7dfd81970501d07e7c438abdd2
https://github.com/solex2006/SELIProject/commit/86bffb5242b4de53eed964cd6df2bdf51f420455

**Comment by CAndresH** [comment]
now the platform has the option for Quiz with time constraint and extended time and no-time options

![image](https://user-images.githubusercontent.com/50594090/78808607-4d266b80-798b-11ea-853f-7389f0b1459a.png)


the test is created according to the chosen configuration (see on the student side)
