### ISSUE TITLE
Quiz time constraint stops to work

### ISSUE THREAD

**Issue by ecureuill** [solex2006/SELIProject#41]
## Expected Behavior

Quiz with time constraint should close after time end.

## Current Behavior

Timer is not starting. Visual feedback of time keep the same and quiz never close. 

## Steps to Reproduce

As a student
1.  Start a quiz with time constraint
1.  Wait for quiz to automatically close
    1. Textual feedback of time never change, e.g., as time goes, it keep showing  "00:02:00" 
    1. As time run out, quiz didn't close

## Environment

Debian SO
Chrome

**Comment by CAndresH** [comment]
This functionality was fixed in feature/40 and feature/39.

**Comment by CAndresH** [comment]
please check
