### ISSUE TITLE
Configure accessibility not enabled for Video Content

### ISSUE THREAD

**Issue by ecureuill** [solex2006/SELIProject#6]
## Expected Behavior

After video content is created, user must have the option to configure the accessibility resources immediately.
## Current Behavior

Only the option to configure the accessibility later is enabled for user.

## Steps to Reproduce

1. Upload a video file
2. Give a title and optionally a external link and description
3. Click the button "create content"

![image](https://user-images.githubusercontent.com/993369/74568907-e1f68500-4f57-11ea-9eb8-7b324d3b08f2.png)

## Issue reference
#2

**Comment by CAndresH** [comment]
this option is enabled now
