### ISSUE TITLE
No feedback of error on File Upload

### ISSUE THREAD

**Issue by ecureuill** [solex2006/SELIProject#68]
When user tries to upload the wrong type of file, as there is no feedcack, for him it will appears that upload function is not working. It's important to give a feedback telling what happened (error) and what to do.

## Expected Behavior

When user tries to upload a wrong file, system gives a feedback.

## Current Behavior
No feedback is presented.

## Steps to Reproduce

1. Opens file dialog ("Click here to upload a audio file")
2. Switch the filter "Audio file" for "All files"
3. Select a *.pdf file
4. Nothing happens

**My suggestion is**
Using the #46 and #49 (chek live-demo) pattern, shows as label 
> :information_source:  Accepted formats are .... less than xxxMb

And in a error, change label color and message
>  :information_source:   It seems you have not choosen an audio file.  Accepted formats are .... less than xxxMb

## Related Issue
#4

**Comment by ecureuill** [comment]
@CAndresH see this #70

**Comment by CAndresH** [comment]
camila i'm going to use the snack bar defined by mateo to alert about the type of file to upload, something like this

![image](https://user-images.githubusercontent.com/50594090/79494877-5944a580-7fe9-11ea-9d93-92c9dd5578e2.png)

**Comment by ecureuill** [comment]
@CAndresH even if you use the snackbar to alert about failed or successful upload, you will still need to work on usability/accessibility of the form #70. The information about the files limitation should be give in advance directly in the form. #48 


Check if the snackbar is already accessible, otherwise follow this:
https://www.w3.org/TR/wai-aria-practices-1.1/#alert

**Comment by CAndresH** [comment]
apparently it was a merge problem, please check now in develop branch
