### ISSUE TITLE
Configure accessibility not enabled for Image Content

### ISSUE THREAD

**Issue by ecureuill** [solex2006/SELIProject#7]
![image](https://user-images.githubusercontent.com/993369/74588507-fe3c0580-4fdb-11ea-8b49-de216348c0cf.png)

## Expected Behavior

After image content is created, user must have the option to configure the accessibility resources immediately.
## Current Behavior

Only the option to configure the accessibility later is enabled for user.

## Steps to Reproduce

1. Upload a image file
2. Give a title and optionally a external link and description
3. Click the button "create content"

## Issue reference
#2 #6

**Comment by CAndresH** [comment]
This option is enabled now.
