### ISSUE TITLE
File Upload must have feedbacks and tips

### ISSUE THREAD

**Issue by ecureuill** [solex2006/SELIProject#70]
Update the file upload component to receive as attribute the feedback and tips

# Implementation
Call the AccessibilityHelp component with the appropriate option

```html
import AccessibilityHelp from '../tools/AccessibilityHelp';
                           <AccessibilityHelp 
					id={'uniq id'} 
					name={'name'} 
					error={props.error} //the function that validate the upload 
					tip={props.tip} 
					/* step={props.step} */
					/* stepLabel={props.stepLabel} */
					language={props.language}
				/>
```

**Comment by CAndresH** [comment]
please attach the text that the tooltip must have and in which position of the component the text should appear

**Comment by ecureuill** [comment]
Is the same of #68

Call the `AccessibilityHelp` right below the upload button with the tip.
> Accepted formats are .... less than xxxMb
The exactly text should be the limitations that you configure in the component 

On error, you change the tip message
>  It seems you have not choosen an audio file.  Accepted formats are .... less than xxxMb

`tip={error? props.tiperror || props.tip}`

**Comment by CAndresH** [comment]
Camila already added the tips on the student and teacher side as follows:

![image](https://user-images.githubusercontent.com/50594090/79801356-98456480-8323-11ea-96de-66eb94dfa1a9.png)

![image](https://user-images.githubusercontent.com/50594090/79801364-9da2af00-8323-11ea-9a52-79a0b1decab6.png)

**Comment by ecureuill** [comment]
No need of a snackbar, since the message is inline.

> ## Functional Test failed!
> Please, review your solution.
> When uploading a wrong file there's a tip (in red) but no snack bar saying a wrong type of file was uploaded

**Comment by CAndresH** [comment]
apparently it was a merge problem, please check now in develop branch
